name: C++ fundamentals - max of vector

on: [pull_request]

jobs:
  fibonacci:
    runs-on: ubuntu-latest
    env:
      path: homework/max-of-vector/build
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir ${{ env.repo }}
    - name: Compile
      working-directory: ${{ env.repo }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.repo }}
      run: ctest -V
